lib: find_next_bit.o needed by a module only, move it from lib to obj
It is possible to configure the kernel such that find_next_bit is
referenced only by modules, causing linking to fail with

ERROR: "find_last_bit" [fs/nfs/nfs.ko] undefined!

Signed-off-by: Fred Isaman <iisaman@citi.umich.edu>
Signed-off-by: Benny Halevy <bhalevy@panasas.com>