FIXME: spnfs: conditionaly compile rpc_mkpipe_compat only for CONFIG_SPNFS
rpc_mkpipe_compat is broken in 2.6.31 since spnfs is the only user of this
function confine the breakage there until fixed.

net/sunrpc/rpc_pipe.c: In function ‘rpc_mkpipe_compat’:
net/sunrpc/rpc_pipe.c:850: error: implicit declaration of function ‘inode_dir_notify’

Signed-off-by: Benny Halevy <bhalevy@panasas.com>